### ISSUE TITLE
Update Adyen Web Drop-in from version `3.23.0` to `5.14.0`

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-adyen#6]
## Documentation

- https://docs.adyen.com/online-payments/web-drop-in/integrated-before-5-0-0
- https://docs.adyen.com/online-payments/web-drop-in

## To-do

- [x] Remove old web SDK gateway.
   https://github.com/pronamic/wp-pronamic-pay-adyen/blob/3.1.0/src/WebSdkGateway.php
- [x] ~~Remove "API-key" setting, use new `clientKey` parameter.~~
   ~~https://github.com/pronamic/wp-pronamic-pay-adyen/blob/3.1.0/src/Integration.php#L226-L240~~
- [x] Remove "Origin Key" setting, no longer used, use new `clientKey` parameter.
   https://github.com/pronamic/wp-pronamic-pay-adyen/blob/3.1.0/src/Integration.php#L260-L278
- [x] Add new `clientKey` setting.
- [x] Add new `environment` setting: `test`, `live`, `live-au`, etc.
   https://docs.adyen.com/online-payments/web-drop-in#test-and-go-live
- [x] https://github.com/pronamic/wp-pronamic-pay-adyen/issues/10
   _As far as I'm concerned we spend very little time on this, maybe a notification and a major version update (`4.0`)._

## Related issues

- [x] https://github.com/pronamic/wp-pronamic-pay-adyen/issues/1
- [x] https://github.com/pronamic/wp-pronamic-pay-adyen/issues/3

**Comment by remcotolsma** [comment]
> - [x] Remove old web SDK gateway.
>    https://github.com/pronamic/wp-pronamic-pay-adyen/blob/3.1.0/src/WebSdkGateway.php

Removed in https://github.com/pronamic/wp-pronamic-pay-adyen/commit/348782efcbfc3a4dbf7e7b9167161702e86129ea.

> - [x] ~~Remove "API-key" setting, use new clientKey parameter.~~
>    ~~https://github.com/pronamic/wp-pronamic-pay-adyen/blob/3.1.0/src/Integration.php#L226-L240~~

API-key is probably still needed for server side communication with Adyen.

> - [x] Remove "Origin Key" setting, no longer used, use new clientKey parameter.
>    https://github.com/pronamic/wp-pronamic-pay-adyen/blob/3.1.0/src/Integration.php#L260-L278
> - [x] Add new clientKey setting.

Removed/added in https://github.com/pronamic/wp-pronamic-pay-adyen/commit/c3d9bf2764b477dbbfe507bcad97106583711965.
